[project]
authors = ["AliPiccioniQC <ali.piccioni@quantco.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "experimental-pixi-pin"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
shellcheck = ">=0.10.0,<0.11"
git = ">=2.47.0,<3"
pre-commit = ">=4.0.1,<5"
make = ">=4.4.1,<5"
